name: Build Project
run-name: build project
on:
  workflow_call:
    inputs:
        project_name:
            required: true
            type: string
        engine_path:
            required: true
            type: string
        extra_args:
            required: false
            type: string
        platform:
          # Mac, IOS, PS5, Android...
            required: false
            type: string
            default: "Win64"
        build_configuration:
          # Debug, Development, Shipping, Test 
            required: false
            type: string
            default: "Shipping"

jobs:
  Build:
    runs-on: self-hosted
    steps:
      - name: Build
        shell: powershell
        run: |
          ${{ inputs.engine_path }}\Engine\Build\BatchFiles\RunUAT.bat BuildCookRun -project="${{ github.workspace }}\${{ inputs.project_name }}.uproject" -targetplatform=${{ inputs.platform }} -noP4 -clientconfig=${{ inputs.build_configuration }} -build -cook -stage -pak -package -archive -archivedirectory="${{ runner.temp }}/Artifact" ${{inputs.extra_args}}
      - name: Upload to github
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: ${{ runner.temp }}/Artifact