name: Build Project
run-name: build project
on:
  workflow_call:
    
    inputs:
        project-name:
            required: true
            type: string
        engine-path:
            required: true
            type: string
        extra-args:
            required: false
            type: string

jobs:
  Build:
    outputs:
      engine_path: ${{steps.get.outputs.engine_path}}
    runs-on: self-hosted
    steps:
      - name: Build
        id: get
        shell: powershell
        run: |
          ${{ inputs.engine-path }}\Engine\Build\BatchFiles\RunUAT.bat BuildCookRun -project=${{ inputs.project-name }}.uproject -targetplatform=Win64 -noP4 -clientconfig=Development -build -cook -stage -pak -package -archive -archivedirectory="${{ github.workspace }}/Artifact" ${{inputs.extra-args}}