name: Build and Publish Binaries
run-name: Building commit  ${{ github.sha }}
on:
  workflow_call:
    inputs:
      project-name:
        required: true
        type: string
      engine-path:
        required: true
        type: string
jobs:
  Build:
# make sure we have permision to write
    permissions: write-all
    runs-on: self-hosted
    steps:
      - run: echo "Trigged by ${{ github.event_name }}, user ${{github.actor}}, branch ${{ github.ref }}"
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: List files in the repository (for debug)
        run: |
          ls ${{ github.workspace }}
      - name: Build the binaries
        # run: D:/UE_5.4/Engine/Binaries/DotNET/UnrealBuildTool/UnrealBuildTool.exe -projectfiles -project="%~dp0\BuildingBinaries1.uproject" -game -engine -progress
        run:  ${{ inputs.engine-path }}/Engine/Build/BatchFiles/RunUAT.bat BuildCookRun -platform=Win64 -clientconfig=Development -project="${{ github.workspace }}\${{ inputs.project-name }}.uproject" -build
      - name: Commit Binaries
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add Binaries/*dll --force
          git add */Binaries/*dll --force
          git commit -m "Binaries for ${{github.sha}}"
          git push
