name: Build Project
run-name: build project
on:
  workflow_call:
    
    inputs:
        project-name:
            required: true
            type: string
        engine-path:
            required: true
            type: string
        extra-args:
            required: false
            type: string

jobs:
  Build:
    runs-on: self-hosted
    steps:
      - name: Build
        shell: powershell
        run: |
          ${{ inputs.engine-path }}\Engine\Build\BatchFiles\RunUAT.bat BuildCookRun -project="${{ github.workspace }}\${{ inputs.project-name }}.uproject" -targetplatform=Win64 -noP4 -clientconfig=Development -build -cook -stage -pak -package -archive -archivedirectory="${{ runner.temp }}/Artifact" ${{inputs.extra-args}}
      - name: Upload to github
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: ${{ runner.temp }}/Artifact