name: Get Engine Path
run-name: Get engine path
on:
  workflow_call:
    inputs:
      engine_version:
        required: true
        type: string
    outputs:
       path:
        description: the string identifying the engine version or custom engine guid
        value: ${{jobs.get_engine_path.outputs.engine_path}}
jobs:
  get_engine_path:
    outputs:
      engine_path: ${{steps.get.outputs.engine_path}}
    runs-on: self-hosted
    steps:
      - name: Get Engine Path
        id: get
        shell: powershell
        run: |
          $EngineVersion = ${{ inputs.engine_version }}
          $EngineInstalationFolder=(Get-ItemPropertyValue -Path "HKLM:\SOFTWARE\EpicGames\Unreal Engine\$EngineVersion" "InstalledDirectory")
          $output = "engine_path=$($EngineInstalationFolder)"
          echo $output
          $output >> $Env:GITHUB_OUTPUT