name: Get Project Engine Association
run-name: Get Project's Engine Association
on:
  workflow_call:
    inputs:
      project_name:
        required: true
        type: string
    outputs:
      engine_association:
        description: the string identifying the engine version or custom engine guid
        value: ${{jobs.get_engine_version.outputs.engine_association}}
jobs:
  get_engine_version:
    runs-on: self-hosted
    outputs:
      engine_association: ${{steps.get.outputs.engine_association}}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Get project's engine association
        id: get
        shell: powershell
        run:  |
         $jsonObject = Get-Content -Path "${{ github.workspace }}\${{ inputs.project-name }}.uproject" | ConvertFrom-JSON
         $engine_association = $jsonObject.EngineAssociation
         $output = "engine_association=$($engine_association)"
         echo $output
         $output >> $Env:GITHUB_OUTPUT
         echo $Env:GITHUB_OUTPUT



         
